services:
  cloudwatch-logs-viewer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ubl-cloudwatch-logs
    ports:
      - "6067:6067"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - cloudwatch-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  cloudwatch-network:
    driver: bridge
